version: 0.0
os: linux

files:
  - source: app.py
    destination: /opt/flask-app
  - source: requirements.txt
    destination: /opt/flask-app
  - source: scripts
    destination: /opt/flask-app/scripts

permissions:
  - object: /opt/flask-app/scripts
    mode: "755"
    type:
      - file

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root
